package org.gbif.api.vocabulary;


import lombok.Getter;

@Getter
public enum DescriptorIssue {
  VOCAB_VALUE_DEPRECATED("VOCAB_VALUE_DEPRECATED"),
  VOCAB_VALUE_MATCHED_LABEL("VOCAB_VALUE_MATCHED_LABEL"),
  VOCAB_VALUE_MATCHED_DEPRECATED_LABEL("VOCAB_VALUE_MATCHED_DEPRECATED_LABEL"),
  VOCAB_VALUE_NOT_FOUND("VOCAB_VALUE_NOT_FOUND"),
  BIOME_TYPE_VALIDATION_ISSUE("BIOME_TYPE_VALIDATION_ISSUE"),
  OBJECT_CLASSIFICATION_VALIDATION_ISSUE("OBJECT_CLASSIFICATION_VALIDATION_ISSUE");

  private final String id;

  DescriptorIssue(String id) {
    this.id = id;
  }
}
